const aptConstants = {
  MAKE_PAYMENT_REQUEST: 'MAKE_PAYMENT_REQUEST',
  MAKE_PAYMENT_SUCCESS: 'MAKE_PAYMENT_SUCCESS',
  MAKE_PAYMENT_FAILURE: 'MAKE_PAYMENT_FAILURE',

  PAYMENT_HIST_REQUEST: 'PAYMENT_HIST_REQUEST',
  PAYMENT_HIST_SUCCESS: 'PAYMENT_HIST_SUCCESS',
  PAYMENT_HIST_FAILURE: 'PAYMENT_HIST_FAILURE',

  MAKE_MAINTENCE_REQ_REQUEST: 'MAKE_MAINTENCE_REQ_REQUEST',
  MAKE_MAINTENCE_REQ_SUCCESS: 'MAKE_MAINTENCE_REQ_SUCCESS',
  MAKE_MAINTENCE_REQ_FAILURE: 'MAKE_MAINTENCE_REQ_FAILURE',

  ALL_MAINTENCE_REQ_REQUEST: 'ALL_MAINTENCE_REQ_REQUEST',
  ALL_MAINTENCE_REQ_SUCCESS: 'ALL_MAINTENCE_REQ_SUCCESS',
  ALL_MAINTENCE_REQ_FAILURE: 'ALL_MAINTENCE_REQ_FAILURE',

  GET_BALANCE_INFO_REQUEST: 'GET_BALANCE_INFO_REQUEST',
  GET_BALANCE_INFO_SUCCESS: 'GET_BALANCE_INFO_SUCCESS',
  GET_BALANCE_INFO_FAILURE: 'GET_BALANCE_INFO_FAILURE',

};

export default aptConstants;
