const messConstants = {
  ALL_CHATROOMS_REQUEST: 'ALL_CHATROOMS_REQUEST',
  ALL_CHATROOMS_SUCCESS: 'ALL_CHATROOMS_SUCCESS',
  ALL_CHATROOMS_FAILURE: 'ALL_CHATROOMS_FAILURE',

  NEW_CHATROOM_REQUEST: 'NEW_CHATROOM_REQUEST',
  NEW_CHATROOM_SUCCESS: 'NEW_CHATROOM_SUCCESS',
  NEW_CHATROOM_FAILURE: 'NEW_CHATROOM_FAILURE',

  DEL_CHATROOM_REQUEST: 'DEL_CHATROOM_REQUEST',
  DEL_CHATROOM_SUCCESS: 'DEL_CHATROOM_SUCCESS',
  DEL_CHATROOM_FAILURE: 'DEL_CHATROOM_FAILURE',

  NEW_MESSAGE_REQUEST: 'NEW_MESSAGE_REQUEST',
  NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
  NEW_MESSAGE_FAILURE: 'NEW_MESSAGE_FAILURE',

  ALL_MESSAGES_REQUEST: 'ALL_MESSAGES_REQUEST',
  ALL_MESSAGES_SUCCESS: 'ALL_MESSAGES_SUCCESS',
  ALL_MESSAGES_FAILURE: 'ALL_MESSAGES_FAILURE',
};

export default messConstants;
